/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BMI;
import javax.swing.JOptionPane;
import static java.awt.PageAttributes.MediaType.C;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author iris
 */
public class BMILogin extends javax.swing.JFrame {
double [] fruit = new double[5];
double [] vegetable = new double[5];
double [] food = new double[5];
double [] calories = new double[4];
double [] other = new double[2];
double [] i = new double[15];
double [] sum = new double[5];
double [] ctotal = new double[6];

double apple = 87.5;
double banana = 105;
double honeymelon = 54;
double strawberry = 49;
double pinapple = 82;

double cauliflower = 25;
double bc = 35;
double lettuce = 15;
double potato = 163;
double tomato = 22;

double chicken = 215;
double fish = 89;
double bread = 69;
double soup = 183.7;
double rice = 232;



    /**
     * Creates new form BMILogin
     */
    public BMILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NameApple = new javax.swing.JCheckBox();
        NameBanana = new javax.swing.JCheckBox();
        NameHoneymelon = new javax.swing.JCheckBox();
        NameStrawberry = new javax.swing.JCheckBox();
        NamePinapple = new javax.swing.JCheckBox();
        Apple = new javax.swing.JTextField();
        Banana = new javax.swing.JTextField();
        Honeymelon = new javax.swing.JTextField();
        Strawberry = new javax.swing.JTextField();
        Pinapple = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        NameChicken = new javax.swing.JCheckBox();
        NameFish = new javax.swing.JCheckBox();
        NameBread = new javax.swing.JCheckBox();
        NameSoup = new javax.swing.JCheckBox();
        NameRice = new javax.swing.JCheckBox();
        Chicken = new javax.swing.JTextField();
        Fish = new javax.swing.JTextField();
        Bread = new javax.swing.JTextField();
        Soup = new javax.swing.JTextField();
        Rice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        NameExercise = new javax.swing.JLabel();
        NameSnacks = new javax.swing.JLabel();
        NameResult = new javax.swing.JLabel();
        Exercise = new javax.swing.JTextField();
        Snacks = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        CheckExercise = new javax.swing.JCheckBox();
        CheckSnacks = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Receipt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Calculate = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Summary = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lable = new javax.swing.JLabel();
        NameCaloriesVegetables = new javax.swing.JLabel();
        NameCaloriesFood = new javax.swing.JLabel();
        NameTakenin = new javax.swing.JLabel();
        cfruit = new javax.swing.JLabel();
        cveg = new javax.swing.JLabel();
        cfood = new javax.swing.JLabel();
        ceat = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NameCauliflower = new javax.swing.JCheckBox();
        NameBabyCarrot = new javax.swing.JCheckBox();
        NameLettuce = new javax.swing.JCheckBox();
        NamePotato = new javax.swing.JCheckBox();
        NameTomato = new javax.swing.JCheckBox();
        Cauliflower = new javax.swing.JTextField();
        BabyCarrot = new javax.swing.JTextField();
        Lettuce = new javax.swing.JTextField();
        Potato = new javax.swing.JTextField();
        Tomato = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Apple LiGothic", 1, 48)); // NOI18N
        jLabel1.setText("Daily Calories Consumption");

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/iris/Desktop/SECOND.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1160, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NameApple.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameApple.setText("Apple");
        NameApple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameAppleMouseClicked(evt);
            }
        });
        NameApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameAppleActionPerformed(evt);
            }
        });

        NameBanana.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameBanana.setText("Banana");
        NameBanana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameBananaMouseClicked(evt);
            }
        });
        NameBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBananaActionPerformed(evt);
            }
        });

        NameHoneymelon.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameHoneymelon.setText("Honeymelon");
        NameHoneymelon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameHoneymelonMouseClicked(evt);
            }
        });
        NameHoneymelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameHoneymelonActionPerformed(evt);
            }
        });

        NameStrawberry.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameStrawberry.setText("Strawberry");
        NameStrawberry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameStrawberryMouseClicked(evt);
            }
        });
        NameStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameStrawberryActionPerformed(evt);
            }
        });

        NamePinapple.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NamePinapple.setText("Pinapple");
        NamePinapple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamePinappleMouseClicked(evt);
            }
        });
        NamePinapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePinappleActionPerformed(evt);
            }
        });

        Apple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Apple.setText("0");
        Apple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Apple.setEnabled(false);
        Apple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppleMouseClicked(evt);
            }
        });
        Apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleActionPerformed(evt);
            }
        });
        Apple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AppleKeyTyped(evt);
            }
        });

        Banana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Banana.setText("0");
        Banana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Banana.setEnabled(false);
        Banana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BananaActionPerformed(evt);
            }
        });
        Banana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BananaKeyTyped(evt);
            }
        });

        Honeymelon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Honeymelon.setText("0");
        Honeymelon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Honeymelon.setEnabled(false);
        Honeymelon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HoneymelonKeyTyped(evt);
            }
        });

        Strawberry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Strawberry.setText("0");
        Strawberry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Strawberry.setEnabled(false);
        Strawberry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StrawberryKeyTyped(evt);
            }
        });

        Pinapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pinapple.setText("0");
        Pinapple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pinapple.setEnabled(false);
        Pinapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinappleActionPerformed(evt);
            }
        });
        Pinapple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PinappleKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Apple LiGothic", 1, 18)); // NOI18N
        jLabel8.setText("Fruit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NameHoneymelon)
                                .addGap(18, 18, 18)
                                .addComponent(Honeymelon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NameStrawberry)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(NameApple)
                                    .addComponent(NameBanana)
                                    .addComponent(NamePinapple))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Pinapple, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(Apple, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Banana, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apple, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameApple))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameBanana)
                    .addComponent(Banana, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameHoneymelon)
                    .addComponent(Honeymelon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameStrawberry)
                    .addComponent(Strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NamePinapple)
                        .addComponent(Pinapple, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 360));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NameChicken.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameChicken.setText("Chicken");
        NameChicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameChickenMouseClicked(evt);
            }
        });
        NameChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameChickenActionPerformed(evt);
            }
        });

        NameFish.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameFish.setText("Fish");
        NameFish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameFishMouseClicked(evt);
            }
        });
        NameFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFishActionPerformed(evt);
            }
        });

        NameBread.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameBread.setText("Bread");
        NameBread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameBreadMouseClicked(evt);
            }
        });
        NameBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBreadActionPerformed(evt);
            }
        });

        NameSoup.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameSoup.setText("Soup");
        NameSoup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameSoupMouseClicked(evt);
            }
        });
        NameSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSoupActionPerformed(evt);
            }
        });

        NameRice.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameRice.setText("Rice");
        NameRice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameRiceMouseClicked(evt);
            }
        });
        NameRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameRiceActionPerformed(evt);
            }
        });

        Chicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Chicken.setText("0");
        Chicken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Chicken.setEnabled(false);
        Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenActionPerformed(evt);
            }
        });
        Chicken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ChickenKeyTyped(evt);
            }
        });

        Fish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fish.setText("0");
        Fish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Fish.setEnabled(false);
        Fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FishActionPerformed(evt);
            }
        });
        Fish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FishKeyTyped(evt);
            }
        });

        Bread.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Bread.setText("0");
        Bread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Bread.setEnabled(false);
        Bread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreadActionPerformed(evt);
            }
        });
        Bread.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BreadKeyTyped(evt);
            }
        });

        Soup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Soup.setText("0");
        Soup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Soup.setEnabled(false);
        Soup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoupActionPerformed(evt);
            }
        });
        Soup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoupKeyTyped(evt);
            }
        });

        Rice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Rice.setText("0");
        Rice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Rice.setEnabled(false);
        Rice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Apple LiGothic", 1, 18)); // NOI18N
        jLabel10.setText("Staple Food");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(NameChicken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(NameFish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(NameBread)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(NameSoup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(NameRice)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Soup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bread, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fish, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(82, 82, 82))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameChicken)
                    .addComponent(Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameFish)
                    .addComponent(Fish, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameBread)
                    .addComponent(Bread, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameSoup)
                    .addComponent(Soup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameRice)
                    .addComponent(Rice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 250, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NameResult.setText("Total");

        Exercise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Exercise.setText("0");
        Exercise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Exercise.setEnabled(false);
        Exercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExerciseActionPerformed(evt);
            }
        });

        Snacks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Snacks.setText("0");
        Snacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Snacks.setEnabled(false);
        Snacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnacksActionPerformed(evt);
            }
        });

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        CheckExercise.setText("Exercise");
        CheckExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckExerciseActionPerformed(evt);
            }
        });

        CheckSnacks.setText("Snacks");
        CheckSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSnacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameExercise)
                    .addComponent(CheckExercise)
                    .addComponent(NameSnacks)
                    .addComponent(CheckSnacks)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(NameResult)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Snacks, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exercise, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameExercise)
                    .addComponent(Exercise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckExercise))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Snacks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameSnacks)
                    .addComponent(CheckSnacks))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameResult)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 380, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Receipt.setColumns(20);
        Receipt.setRows(5);
        jScrollPane1.setViewportView(Receipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 370, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Summary.setText("Summary");
        Summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryActionPerformed(evt);
            }
        });

        Exit.setText("Quit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Summary, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calculate)
                    .addComponent(Reset)
                    .addComponent(Summary)
                    .addComponent(Exit))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, 370, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        lable.setText("Calories For Fruit");

        NameCaloriesVegetables.setText("Calories For Vegetables");

        NameCaloriesFood.setText("Calories For Staple Food");

        NameTakenin.setText("Calories taken in");

        cfruit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cfruit.setText("0");
        cfruit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cveg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cveg.setText("0");
        cveg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cfood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cfood.setText("0");
        cfood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ceat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ceat.setText("0");
        ceat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lable)
                    .addComponent(NameCaloriesVegetables)
                    .addComponent(NameTakenin)
                    .addComponent(NameCaloriesFood))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cfruit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cveg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(cfood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ceat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lable))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cfruit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cveg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(NameCaloriesVegetables)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NameCaloriesFood)
                        .addGap(29, 29, 29)
                        .addComponent(NameTakenin)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cfood, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ceat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 390, 220));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NameCauliflower.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameCauliflower.setText("Cauliflower");
        NameCauliflower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameCauliflowerMouseClicked(evt);
            }
        });
        NameCauliflower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameCauliflowerActionPerformed(evt);
            }
        });

        NameBabyCarrot.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameBabyCarrot.setText("Baby Carrot");
        NameBabyCarrot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameBabyCarrotMouseClicked(evt);
            }
        });
        NameBabyCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBabyCarrotActionPerformed(evt);
            }
        });

        NameLettuce.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameLettuce.setText("Lettuce");
        NameLettuce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameLettuceMouseClicked(evt);
            }
        });
        NameLettuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameLettuceActionPerformed(evt);
            }
        });

        NamePotato.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NamePotato.setText("Potato");
        NamePotato.setToolTipText("");
        NamePotato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamePotatoMouseClicked(evt);
            }
        });
        NamePotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePotatoActionPerformed(evt);
            }
        });

        NameTomato.setFont(new java.awt.Font("Apple LiGothic", 1, 14)); // NOI18N
        NameTomato.setText("Tomato");
        NameTomato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameTomatoMouseClicked(evt);
            }
        });
        NameTomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTomatoActionPerformed(evt);
            }
        });

        Cauliflower.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cauliflower.setText("0");
        Cauliflower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Cauliflower.setEnabled(false);
        Cauliflower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CauliflowerActionPerformed(evt);
            }
        });
        Cauliflower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CauliflowerKeyTyped(evt);
            }
        });

        BabyCarrot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BabyCarrot.setText("0");
        BabyCarrot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BabyCarrot.setEnabled(false);
        BabyCarrot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BabyCarrotKeyTyped(evt);
            }
        });

        Lettuce.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lettuce.setText("0");
        Lettuce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Lettuce.setEnabled(false);
        Lettuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LettuceActionPerformed(evt);
            }
        });
        Lettuce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LettuceKeyTyped(evt);
            }
        });

        Potato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Potato.setText("0");
        Potato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Potato.setEnabled(false);
        Potato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PotatoKeyTyped(evt);
            }
        });

        Tomato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tomato.setText("0");
        Tomato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Tomato.setEnabled(false);
        Tomato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TomatoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Apple LiGothic", 1, 18)); // NOI18N
        jLabel9.setText("Vegetable");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(NameBabyCarrot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(NameLettuce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(NamePotato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(NameTomato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel7))
                            .addComponent(NameCauliflower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cauliflower, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tomato, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Potato, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lettuce, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BabyCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cauliflower, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameCauliflower))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBabyCarrot)
                            .addComponent(BabyCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLettuce)
                            .addComponent(Lettuce, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamePotato)
                            .addComponent(Potato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTomato)
                            .addComponent(Tomato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jLabel7))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 250, 360));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CauliflowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CauliflowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CauliflowerActionPerformed

    private void LettuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LettuceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LettuceActionPerformed

    private void ChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChickenActionPerformed

    private void FishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FishActionPerformed

    private void BreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BreadActionPerformed

    private void SoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoupActionPerformed

    private void RiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RiceActionPerformed

    private void NameBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBananaActionPerformed
        // TODO add your handling code here:
        if(NameBanana.isSelected())
        {
            Banana.setEnabled(true);
            Banana.requestFocus();
            Banana.setText("");
        }
        else
        {
            Banana.setEnabled(false);
            Banana.setText("0");
        }
    }//GEN-LAST:event_NameBananaActionPerformed

    private void NameFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFishActionPerformed
        // TODO add your handling code here:
        if(NameFish.isSelected())
        {
            Fish.setEnabled(true);
            Fish.requestFocus();
            Fish.setText("");
        }
        else
        {
            Fish.setEnabled(false);
            Fish.setText("0");
        }
    }//GEN-LAST:event_NameFishActionPerformed

    private void NameCauliflowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameCauliflowerActionPerformed
        // TODO add your handling code here:
        if(NameCauliflower.isSelected())
        {
            Cauliflower.setEnabled(true);
            Cauliflower.requestFocus();
            Cauliflower.setText("");
        }
        else
        {
            Cauliflower.setEnabled(false);
            Cauliflower.setText("0");
        }
    }//GEN-LAST:event_NameCauliflowerActionPerformed

    private void NameAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAppleActionPerformed
        // TODO add your handling code here:
        if(NameApple.isSelected())
        {
            Apple.setEnabled(true);
            Apple.requestFocus();
            Apple.setText("");
        }
        else
        {
            Apple.setEnabled(false);
            Apple.setText("0");
        }
    }//GEN-LAST:event_NameAppleActionPerformed

    private void AppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleActionPerformed

    private void ExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExerciseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExerciseActionPerformed

    private void SnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnacksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnacksActionPerformed

    private void NameHoneymelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameHoneymelonActionPerformed
        // TODO add your handling code here:
        if(NameHoneymelon.isSelected())
        {
            Honeymelon.setEnabled(true);
            Honeymelon.requestFocus();
            Honeymelon.setText("");
        }
        else
        {
            Honeymelon.setEnabled(false);
            Honeymelon.setText("0");
        }
    }//GEN-LAST:event_NameHoneymelonActionPerformed

    private void NameStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameStrawberryActionPerformed
        // TODO add your handling code here:
        if(NameStrawberry.isSelected())
        {
            Strawberry.setEnabled(true);
            Strawberry.requestFocus();
            Strawberry.setText("");
        }
        else
        {
            Strawberry.setEnabled(false);
            Strawberry.setText("0");
        }
    }//GEN-LAST:event_NameStrawberryActionPerformed

    private void NamePinappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePinappleActionPerformed
        // TODO add your handling code here:
        if(NamePinapple.isSelected())
        {
            Pinapple.setEnabled(true);
            Pinapple.requestFocus();
            Pinapple.setText("");
        }
        else
        {
            Pinapple.setEnabled(false);
            Pinapple.setText("0");
        }
    }//GEN-LAST:event_NamePinappleActionPerformed

    private void NameCauliflowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameCauliflowerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameCauliflowerMouseClicked

    private void NameBabyCarrotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameBabyCarrotMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NameBabyCarrotMouseClicked

    private void NameLettuceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameLettuceMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NameLettuceMouseClicked

    private void NamePotatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamePotatoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NamePotatoMouseClicked

    private void NameTomatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTomatoMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NameTomatoMouseClicked

    private void NameLettuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameLettuceActionPerformed
        // TODO add your handling code here:
        if(NameLettuce.isSelected())
        {
            Lettuce.setEnabled(true);
            Lettuce.requestFocus();
            Lettuce.setText("");
        }
        else
        {
            Lettuce.setEnabled(false);
            Lettuce.setText("0");
        }
    }//GEN-LAST:event_NameLettuceActionPerformed

    private void PinappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinappleActionPerformed

    private void NameAppleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameAppleMouseClicked
        // TODO add your handling code here:
        double apple = Double.parseDouble(Apple.getText());
        double capple = Double.parseDouble(cfruit.getText());
        if(NameApple.isSelected())
        {
            i[0] = (apple*87.5) + capple;
            String caloriesa = String.format("%.2f",i[0]);
            cfruit.setText(caloriesa);
        }
    }//GEN-LAST:event_NameAppleMouseClicked

    private void NameBananaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameBananaMouseClicked
        // TODO add your handling code here:
        double banana = Double.parseDouble(Banana.getText());
        double cbanana = Double.parseDouble(cfruit.getText());
        if(NameBanana.isSelected())
        {
            i[1] = (banana*105)+cbanana;
            String caloriesb = String.format("%.2f",i[1]);
            cfruit.setText(caloriesb);
        }
    }//GEN-LAST:event_NameBananaMouseClicked

    private void NameHoneymelonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameHoneymelonMouseClicked
        // TODO add your handling code here:
        double honeymelon = Double.parseDouble(Honeymelon.getText());
        double chm = Double.parseDouble(cfruit.getText());
        if(NameHoneymelon.isSelected())
        {
            i[2] = (honeymelon*54)+chm;
            String caloriesh = String.format("%.2f",i[2]);
            cfruit.setText(caloriesh);
        }
    }//GEN-LAST:event_NameHoneymelonMouseClicked

    private void NameStrawberryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameStrawberryMouseClicked
        // TODO add your handling code here:
        double strawberry = Double.parseDouble(Strawberry.getText());
        double csb = Double.parseDouble(cfruit.getText());
        if(NameStrawberry.isSelected())
        {
            i[3] = (strawberry*49)+csb;
            String caloriess = String.format("%.2f",i[3]);
            cfruit.setText(caloriess);
        }
    }//GEN-LAST:event_NameStrawberryMouseClicked

    private void NamePinappleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamePinappleMouseClicked
        // TODO add your handling code here:
        double pinapple = Double.parseDouble(Pinapple.getText());
        double cpn = Double.parseDouble(cfruit.getText());
        if(NamePinapple.isSelected())
        {
            i[4] = (pinapple*82)+cpn;
            String caloriescpn = String.format("%.2f",i[4]);
            cfruit.setText(caloriescpn);
        }
    }//GEN-LAST:event_NamePinappleMouseClicked

    private void NameBabyCarrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBabyCarrotActionPerformed
        // TODO add your handling code here:
        if(NameBabyCarrot.isSelected())
        {
            BabyCarrot.setEnabled(true);
            BabyCarrot.requestFocus();
            BabyCarrot.setText("");
        }
        else
        {
            BabyCarrot.setEnabled(false);
            BabyCarrot.setText("0");
        }
    }//GEN-LAST:event_NameBabyCarrotActionPerformed

    private void NameChickenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameChickenMouseClicked
        // TODO add your handling code here:
        double chicken = Double.parseDouble(Chicken.getText());
        double cck = Double.parseDouble(cfood.getText());
        if(NameChicken.isSelected())
        {
            i[10] = (chicken*215)+cck;
            String caloriesck = String.format("%.2f",i[10]);
            cfood.setText(caloriesck);
        }
    }//GEN-LAST:event_NameChickenMouseClicked

    private void NameChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameChickenActionPerformed
        // TODO add your handling code here:
        if(NameChicken.isSelected())
        {
            Chicken.setEnabled(true);
            Chicken.requestFocus();
            Chicken.setText("");
        }
        else
        {
            Chicken.setEnabled(false);
            Chicken.setText("0");
        }
    }//GEN-LAST:event_NameChickenActionPerformed

    private void NameFishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFishMouseClicked
        // TODO add your handling code here:
        double fish = Double.parseDouble(Fish.getText());
        double cfish = Double.parseDouble(cfood.getText());
        if(NameFish.isSelected())
        {
            i[11] = (fish*89)+cfish;
            String caloriesfish = String.format("%.2f",i[11]);
            cfood.setText(caloriesfish);
        }
    }//GEN-LAST:event_NameFishMouseClicked

    private void NameBreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameBreadMouseClicked
        // TODO add your handling code here:
        double bread = Double.parseDouble(Bread.getText());
        double cbread = Double.parseDouble(cfood.getText());
        if(NameBread.isSelected())
        {
            i[12] = (bread*69)+cbread;
            String caloriesbread = String.format("%.2f",i[12]);
            cfood.setText(caloriesbread);
        }
    }//GEN-LAST:event_NameBreadMouseClicked

    private void NameSoupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameSoupMouseClicked
        // TODO add your handling code here:
        double soup = Double.parseDouble(Soup.getText());
        double csoup = Double.parseDouble(cfood.getText());
        if(NameSoup.isSelected())
        {
            i[13] = (soup*183.7)+csoup;
            String caloriessoup = String.format("%.2f",i[13]);
            cfood.setText(caloriessoup);
        }
    }//GEN-LAST:event_NameSoupMouseClicked

    private void NameRiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameRiceMouseClicked
        // TODO add your handling code here:
        double rice = Double.parseDouble(Rice.getText());
        double crice = Double.parseDouble(cfood.getText());
        if(NameRice.isSelected())
        {
            i[14] = (rice*232)+crice;
            String caloriesrice = String.format("%.2f",i[14]);
            cfood.setText(caloriesrice);
        }
    }//GEN-LAST:event_NameRiceMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    Component frame = null;
        
        if(JOptionPane.showConfirmDialog(frame, "Confirm to exit?", "Daily Calories Consumption", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_ExitActionPerformed

    private void SummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryActionPerformed
        fruit[0] = Double.parseDouble(Apple.getText());
        fruit[1] = Double.parseDouble(Banana.getText());
        fruit[2] = Double.parseDouble(Honeymelon.getText());
        fruit[3] = Double.parseDouble(Strawberry.getText());
        fruit[4] = Double.parseDouble(Pinapple.getText());

        vegetable[0] = Double.parseDouble(Cauliflower.getText());
        vegetable[1] = Double.parseDouble(BabyCarrot.getText());
        vegetable[2] = Double.parseDouble(Lettuce.getText());
        vegetable[3] = Double.parseDouble(Potato.getText());
        vegetable[4] = Double.parseDouble(Tomato.getText());

        food[0] = Double.parseDouble(Chicken.getText());
        food[1] = Double.parseDouble(Fish.getText());
        food[2] = Double.parseDouble(Bread.getText());
        food[3] = Double.parseDouble(Soup.getText());
        food[4] = Double.parseDouble(Rice.getText());

        other[0] = Double.parseDouble(Exercise.getText());
        other[1] = Double.parseDouble(Snacks.getText());

        sum[0] = Double.parseDouble(cfruit.getText());
        sum[1] = Double.parseDouble(cveg.getText());
        sum[2] = Double.parseDouble(cfood.getText());

        double grandtotal = sum[0]+sum[1]+sum[2]-other[0]+other[1];

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());

        Receipt.append("\t\nDaily Calories Consumption\n\n" +
            "\n==============================\t\t"+
            "\nFruit:"+
            "\nApple:\t\t\t"+fruit[0]+
            "\nBanana:\t\t\t"+fruit[1]+
            "\nHoneymelon:\t\t\t"+fruit[2]+
            "\nStrawberry:\t\t\t"+fruit[3]+
            "\nPinapple:\t\t\t"+fruit[4]+
            "\n==============================\t\t"+
            "\nVegetables:"+
            "\nCauliflower:\t\t\t"+vegetable[0]+
            "\nBaby Carrot:\t\t\t"+vegetable[1]+
            "\nLettuce:\t\t\t"+vegetable[2]+
            "\nPotato:\t\t\t"+vegetable[3]+
            "\nTomato:\t\t\t"+vegetable[4]+
            "\n==============================\t\t"+
            "\nStaple Foods:"+
            "\nChicken:\t\t\t"+food[0]+
            "\nFish:\t\t\t"+food[1]+
            "\nBread:\t\t\t"+food[2]+
            "\nSoup:\t\t\t"+food[3]+
            "\nRice:\t\t\t"+food[4]+
            "\n==============================\t\t"+
            "\nCalories for fruit:\t\t"+cfruit.getText()+
            "\nCalories for vegetable:\t\t"+cveg.getText()+
            "\nCalories for staple food:\t\t"+cfood.getText()+
            "\nCalories taken in:\t\t"+ceat.getText()+
            "\nExercise:\t\t\t"+other[0]+
            "\nSnacks:\t\t\t"+other[1]+
            "\nSummary:\t\t\t"+grandtotal+
            "\n==============================\t\t"+
            "\nDate: "+Tdate.format(timer.getTime())+
            "\nTime: "+tTime.format(timer.getTime())+
            "\n\nHold on to this! You're almost there!");
    }//GEN-LAST:event_SummaryActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Receipt.setText(null);
        
        Apple.setText("0");
        Banana.setText("0");
        Honeymelon.setText("0");
        Strawberry.setText("0");
        Pinapple.setText("0");
        
        Cauliflower.setText("0");
        BabyCarrot.setText("0");
        Lettuce.setText("0");
        Potato.setText("0");
        Tomato.setText("0");
        
        Chicken.setText("0");
        Fish.setText("0");
        Bread.setText("0");
        Soup.setText("0");
        Rice.setText("0");
        
        Apple.setEnabled(false);
        Banana.setEnabled(false);
        Honeymelon.setEnabled(false);
        Strawberry.setEnabled(false);
        Pinapple.setEnabled(false);
        
        Cauliflower.setEnabled(false);
        BabyCarrot.setEnabled(false);
        Lettuce.setEnabled(false);
        Potato.setEnabled(false);
        Tomato.setEnabled(false);
        
        Chicken.setEnabled(false);
        Fish.setEnabled(false);
        Bread.setEnabled(false);
        Soup.setEnabled(false);
        Rice.setEnabled(false);
        
        Exercise.setEnabled(false);
        Snacks.setEnabled(false);
        
        NameApple.setSelected(false);
        NameBanana.setSelected(false);
        NameHoneymelon.setSelected(false);
        NameStrawberry.setSelected(false);
        NamePinapple.setSelected(false);
        
        NameCauliflower.setSelected(false);
        NameBabyCarrot.setSelected(false);
        NameLettuce.setSelected(false);
        NamePotato.setSelected(false);
        NameTomato.setSelected(false);
        
        NameChicken.setSelected(false);
        NameFish.setSelected(false);
        NameBread.setSelected(false);
        NameSoup.setSelected(false);
        NameRice.setSelected(false);
        
        CheckExercise.setSelected(false);
        CheckSnacks.setSelected(false);
        
        cfruit.setText("0");
        cveg.setText("0");
        cfood.setText("0");
        ceat.setText("0");
        
        Exercise.setText("0");
        Snacks.setText("0");
        
        total.setText("0");
        
        
    }//GEN-LAST:event_ResetActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
        fruit[0] = Double.parseDouble(Apple.getText());
        fruit[1] = Double.parseDouble(Banana.getText());
        fruit[2] = Double.parseDouble(Honeymelon.getText());
        fruit[3] = Double.parseDouble(Strawberry.getText());
        fruit[4] = Double.parseDouble(Pinapple.getText());

        vegetable[0] = Double.parseDouble(Cauliflower.getText());
        vegetable[1] = Double.parseDouble(BabyCarrot.getText());
        vegetable[2] = Double.parseDouble(Lettuce.getText());
        vegetable[3] = Double.parseDouble(Potato.getText());
        vegetable[4] = Double.parseDouble(Tomato.getText());

        food[0] = Double.parseDouble(Chicken.getText());
        food[1] = Double.parseDouble(Fish.getText());
        food[2] = Double.parseDouble(Bread.getText());
        food[3] = Double.parseDouble(Soup.getText());
        food[4] = Double.parseDouble(Rice.getText());

        other[0] = Double.parseDouble(Exercise.getText());
        other[1] = Double.parseDouble(Snacks.getText());
        
        double fruittotal = fruit[0]*apple + fruit[1]*banana + fruit[2]*honeymelon + fruit[3]*strawberry + fruit[4]*pinapple;
        double vegetabletotal = vegetable[0]*cauliflower + vegetable[1]*bc + vegetable[2]*lettuce + vegetable[3]*potato + vegetable[4]*tomato;
        double foodtotal = food[0]*chicken + food[1]*fish + food[2]*bread + food[3]*soup + food[4]*rice;
        
        String convertfruit = String.format("%.2f",fruittotal);
        String convertveg = String.format("%.2f",vegetabletotal);
        String convertfood = String.format("%.2f",foodtotal);
        
        cfruit.setText(convertfruit);
        cveg.setText(convertveg);
        cfood.setText(convertfood);

        double totaleat = fruittotal+vegetabletotal+foodtotal;
        String eatin = String.format("%.2f",totaleat);
        ceat.setText(eatin);
        
        double totalcalories = totaleat-other[0]+other[1];
        String iTotal = String.format("%.2f",totalcalories);
        total.setText(iTotal);
    }//GEN-LAST:event_CalculateActionPerformed

    private void AppleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AppleKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_AppleKeyTyped

    private void NamePotatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePotatoActionPerformed
        // TODO add your handling code here:
        if(NamePotato.isSelected())
        {
            Potato.setEnabled(true);
            Potato.requestFocus();
            Potato.setText("");
        }
        else
        {
            Potato.setEnabled(false);
            Potato.setText("0");
        }
    }//GEN-LAST:event_NamePotatoActionPerformed

    private void NameTomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTomatoActionPerformed
        // TODO add your handling code here:
        if(NameTomato.isSelected())
        {
            Tomato.setEnabled(true);
            Tomato.requestFocus();
            Tomato.setText("");
        }
        else
        {
            Tomato.setEnabled(false);
            Tomato.setText("0");
        }
    }//GEN-LAST:event_NameTomatoActionPerformed

    private void NameBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBreadActionPerformed
        // TODO add your handling code here:
        if(NameBread.isSelected())
        {
            Bread.setEnabled(true);
            Bread.requestFocus();
            Bread.setText("");
        }
        else
        {
            Bread.setEnabled(false);
            Bread.setText("0");
        }
    }//GEN-LAST:event_NameBreadActionPerformed

    private void NameSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSoupActionPerformed
        // TODO add your handling code here:
        if(NameSoup.isSelected())
        {
            Soup.setEnabled(true);
            Soup.requestFocus();
            Soup.setText("");
        }
        else
        {
            Soup.setEnabled(false);
            Soup.setText("0");
        }
    }//GEN-LAST:event_NameSoupActionPerformed

    private void NameRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRiceActionPerformed
        // TODO add your handling code here:
        if(NameRice.isSelected())
        {
            Rice.setEnabled(true);
            Rice.requestFocus();
            Rice.setText("");
        }
        else
        {
            Rice.setEnabled(false);
            Rice.setText("0");
        }
    }//GEN-LAST:event_NameRiceActionPerformed

    private void BananaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BananaKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_BananaKeyTyped

    private void HoneymelonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HoneymelonKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_HoneymelonKeyTyped

    private void StrawberryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StrawberryKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_StrawberryKeyTyped

    private void PinappleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PinappleKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PinappleKeyTyped

    private void CauliflowerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CauliflowerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_CauliflowerKeyTyped

    private void BabyCarrotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BabyCarrotKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_BabyCarrotKeyTyped

    private void LettuceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LettuceKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_LettuceKeyTyped

    private void PotatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PotatoKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PotatoKeyTyped

    private void TomatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TomatoKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_TomatoKeyTyped

    private void ChickenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChickenKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_ChickenKeyTyped

    private void FishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FishKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_FishKeyTyped

    private void BreadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BreadKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_BreadKeyTyped

    private void SoupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoupKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACK_SPACE)
        ||(iNumber == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_SoupKeyTyped

    private void AppleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleMouseClicked

    private void CheckExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckExerciseActionPerformed
        // TODO add your handling code here:
        if(CheckExercise.isSelected())
        {
            Exercise.setEnabled(true);
            Exercise.requestFocus();
            Exercise.setText("");
        }
        else
        {
            Exercise.setEnabled(false);
            Exercise.setText("0");
        }
    }//GEN-LAST:event_CheckExerciseActionPerformed

    private void CheckSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSnacksActionPerformed
        // TODO add your handling code here:
        if(CheckSnacks.isSelected())
        {
            Snacks.setEnabled(true);
            Snacks.requestFocus();
            Snacks.setText("");
        }
        else
        {
            Snacks.setEnabled(false);
            Snacks.setText("0");
        }
    }//GEN-LAST:event_CheckSnacksActionPerformed

    private void BananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BananaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apple;
    private javax.swing.JTextField BabyCarrot;
    private javax.swing.JTextField Banana;
    private javax.swing.JTextField Bread;
    private javax.swing.JButton Calculate;
    private javax.swing.JTextField Cauliflower;
    private javax.swing.JCheckBox CheckExercise;
    private javax.swing.JCheckBox CheckSnacks;
    private javax.swing.JTextField Chicken;
    private javax.swing.JTextField Exercise;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Fish;
    private javax.swing.JTextField Honeymelon;
    private javax.swing.JTextField Lettuce;
    private javax.swing.JCheckBox NameApple;
    private javax.swing.JCheckBox NameBabyCarrot;
    private javax.swing.JCheckBox NameBanana;
    private javax.swing.JCheckBox NameBread;
    private javax.swing.JLabel NameCaloriesFood;
    private javax.swing.JLabel NameCaloriesVegetables;
    private javax.swing.JCheckBox NameCauliflower;
    private javax.swing.JCheckBox NameChicken;
    private javax.swing.JLabel NameExercise;
    private javax.swing.JCheckBox NameFish;
    private javax.swing.JCheckBox NameHoneymelon;
    private javax.swing.JCheckBox NameLettuce;
    private javax.swing.JCheckBox NamePinapple;
    private javax.swing.JCheckBox NamePotato;
    private javax.swing.JLabel NameResult;
    private javax.swing.JCheckBox NameRice;
    private javax.swing.JLabel NameSnacks;
    private javax.swing.JCheckBox NameSoup;
    private javax.swing.JCheckBox NameStrawberry;
    private javax.swing.JLabel NameTakenin;
    private javax.swing.JCheckBox NameTomato;
    private javax.swing.JTextField Pinapple;
    private javax.swing.JTextField Potato;
    private javax.swing.JTextArea Receipt;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Rice;
    private javax.swing.JTextField Snacks;
    private javax.swing.JTextField Soup;
    private javax.swing.JTextField Strawberry;
    private javax.swing.JButton Summary;
    private javax.swing.JTextField Tomato;
    private javax.swing.JLabel ceat;
    private javax.swing.JLabel cfood;
    private javax.swing.JLabel cfruit;
    private javax.swing.JLabel cveg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
